version: "3"

services:
  app:
    container_name: app_bank
    build: .
    ports:
      - "50051:50051"
    volumes:
      - .:/go/src

  db:
    image: postgres:14
    restart: always
    volumes:
      - .dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=codebank
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "9000:80"
    depends_on:
      - db